from .calendar_chart.calendar_chart_chapter import CalendarChartChapterAdmin
from .calendar_chart.calendar_chart_theme import CalendarChartThemeAdmin

from .planning_parameter import PlanningParameterAdmin

from .program import ProgramAdmin

from .services.education_service import EducationServiceAdmin
from .services.information_service import InformationServiceAdmin
