from apps.commons.drf.routers.LRCUDE_router import ListRetrieveCreateUpdateDeleteExportRouter
from apps.edu.api.services.education_service import EducationServiceViewSet

education_service_router = ListRetrieveCreateUpdateDeleteExportRouter(trailing_slash=True)
education_service_router.register('education_service', EducationServiceViewSet)

