from apps.commons.drf.routers.LCUD_router import ListCreateUpdateDeleteRouter
from apps.surveys.api.survey_question_answer import SurveyQuestionAnswerViewSet

survey_question_answer_router = ListCreateUpdateDeleteRouter(trailing_slash=True)
survey_question_answer_router.register('survey_question_answer', SurveyQuestionAnswerViewSet)
