# Generated by Django 4.2.7 on 2024-04-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='module',
            field=models.CharField(choices=[('COMMON', 'Общий'), ('ADMINS', 'ЛК Администратора'), ('APPLICATIONS', 'Модуль заявок'), ('AUTHEN', 'Модуль авторизации/регистрации'), ('CELERY', 'Модуль очереди задач Celery'), ('DOCS', 'Модуль документов'), ('EDU', 'Модуль учебной части'), ('GUIDES', 'Модуль справочников'), ('JOURNAL', 'Модуль журнала событий'), ('REPORTS', 'Модуль отчетов'), ('SETTINGS', 'Модуль настроек'), ('SURVEYS', 'Модуль опросов'), ('USERS', 'ЛК Пользователя')], default='COMMON', max_length=35, verbose_name='Модуль АИС'),
        ),
    ]
