# Generated by Django 4.2.7 on 2024-04-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, default='', max_length=150000, verbose_name='Краткое описание результата события'),
        ),
        migrations.AlterField(
            model_name='journaloutput',
            name='journal_rec',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.journal', verbose_name='Запись журнала событий'),
        ),
        migrations.AlterField(
            model_name='journalpayload',
            name='journal_rec',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.journal', verbose_name='Запись журнала событий'),
        ),
    ]
