# Generated by Django 4.2.7 on 2024-06-07 09:39

import apps.docs.services.program_order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_alter_programorder_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programorder',
            name='file',
            field=models.FileField(max_length=1000, null=True, upload_to=apps.docs.services.program_order.ProgramOrderService.get_upload_path, verbose_name='Файл приказа'),
        ),
    ]
